### ISSUE TITLE
(Request) Backwards compatibility with QT 5.12.

### ISSUE THREAD

**Issue by alphafox02** [cropinghigh/qstdcdec#1]
Would it be possible to support the QT found in Ubuntu 20.04? When trying to build I realized some things must have changed in newer QT versions, as it builds okay in 22.04, but not on 20.04. 

On aarch64 22.04 it runs nicely.

**Comment by cropinghigh** [comment]
As i remember, this project was started when qt5 was the only available version, so it should support it. Can you say, please, what exactly it wants to compile it for qt5?

**Comment by alphafox02** [comment]
I've since updated to 22.04, but went back and checked again on 20.04 which has QT 5.12. During the make process it has an issue here,

`canning dependencies of target qstdcdec
[ 40%] Building CXX object CMakeFiles/qstdcdec.dir/main.cpp.o
[ 60%] Building CXX object CMakeFiles/qstdcdec.dir/qstdcdec_autogen/mocs_compilation.cpp.o                                                                
[ 80%] Building CXX object CMakeFiles/qstdcdec.dir/qstdcdec.cpp.o
/home/cema/qstdcdec/qstdcdec.cpp: In constructor ‘QStdcdec::QStdcdec(QWidget*)’:
/home/cema/qstdcdec/qstdcdec.cpp:20:43: error: ‘errorOccurred’ is not a member of ‘QUdpSocket’
   20 |     connect(&receiverSocket, &QUdpSocket::errorOccurred, this, &QStdcdec::socketErrorOccurred);
      |                                           ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/qstdcdec.dir/build.make:89: CMakeFiles/qstdcdec.dir/qstdcdec.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:77: CMakeFiles/qstdcdec.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

I recall tracking down maybe what was causing it, but then running into another problem after trying to make changes to overcome this. Hope this helps.
